### ISSUE TITLE
It's still in developmenting?

### ISSUE THREAD

**Issue by Alynva** [CrosseyeJack/twitch-giveaways#1]
I tested you extension, and I think that the problem is that you're trying to load chat from `https://www.twitch.tv/user/chat`, but, in the [Twtich's Doc](https://dev.twitch.tv/docs/embed/chat/), the correct URL to load chat embeded is `https://www.twitch.tv/embed/user/chat`. I'm not familiar with extensions, so I can't test this change and make an PR, but it would be much useful.

**Comment by CrosseyeJack** [comment]
Nope sorry. I did a quick hack to customize it to the needs of the mods I work with and made those changes available.

The issue is basically Twitch changed their web chat interface and I deemed it too much of a drain of my own resources to "fix" this version of the code (I'm not the orig dev) to work with the new version and I would basically have to rewrite it from the ground up (The project depends on a number of other abandoned repos).

Is creating a new version still on the cards? Kinda. From working with the mods and going a number of giveaways myself I found that basically it was better for us to integrate a giveaway system into my bot instead of having a Chrome extension (Having bot handle processing of entries/channel settings/rolling the giveaways/etc meant that mods wouldn't select the wrong options as they were the same across everyone, One mod could set up a giveaway and another roll it if the first had to step away and allowed for better auditing of the giveaways just to name a few issues I had with a "single user" system like this extension). Atm those the bot is a private bot so not avilable to the gen public but when I get some time I can work on some free projects for the fun of it I'll prob convert it over to a public system).

EDIT: Just a note, its not as simple as changing the URL for the chat, the actual chat interface this extension was based on has changed on twitch's side. If it was as simple as a quick URL change to get it up and running again I would of done it.
